# (string) Title of your wik
title: OldMotherDota2
#demo_ver: 1.0.13
#remote_theme: Drassil/git-wiki-theme@master
description: OldMother组Dota2社团-OldMother刀刀社主页
show_downloads: false
show_wiki_pages: true
show_wiki_pages_limit: 10
paginate: 5
paginate_path: "assets/blog/page:num"
blog_feature: true
show_wiki_posts: true
show_wiki_posts_limit: 10
logo_url: assets/images/1200px-Wikipedia-logo-v2.svg_.png
google_analytics:
git_branch: main
use_github_wiki: false
use_prose_io: false
service: github
search_engine : "js"
#google_cse_token: 007197903287787072094:8rbvkeqo6qw
wiki_folder : "wiki"
permalink: /blog/posts/:year/:month/:day/:title:output_ext
site_root: 

#
# Jekyll configurations
#

# You can customize it changing default layout for all pages
# More info: https://jekyllrb.com/docs/configuration/
#
# git-wiki includes some internal themes that you can choose
# check _layouts folder
#
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
 - 
    scope:
      path: "wiki"
    values:
      permalink: /:basename
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "git-wiki-post"
 -
    scope:
      path: assets/blog
    values:
      layout: "git-wiki-blog"
sass:
    style: compressed
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji


#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_before_toc : 
inc_after_toc : 
inc_before_content : 
#inc_after_content: "drassil/comments.html"
inc_before_footer : 
inc_after_footer : 
inc_before_head : 
inc_after_head : 
inc_before_meta : 
inc_after_meta : 
inc_before_scripts : 
inc_after_scripts : 
inc_before_styles : 
inc_after_styles : 
inc_before_header : 
inc_after_head : "drassil/head.html"
inc_after_header : "drassil/head.html"
inc_before_tail : 
inc_after_tail : 
inc_before_tools : 
inc_after_tools : 

inc_before_page_list : "drassil/sidebar.html"
inc_after_page_list :
inc_before_post_list :
inc_after_post_list :
